[package]
authors = ["Ceri Storey <ceri@lshift.net>"]
name = "stomping"
version = "0.1.0"

[dependencies]
log = "0.3.6"
failure = "0.1.5"
failure_derive = "0.1.5"

[dev-dependencies]
clap = "2.10.2"
env_logger = "0.6.1"
url = "1.2.0"
uuid = { version = "0.3.1", features = ["v4"] }


[features]
# To skip end to end tests on CI
skip-end-to-end = []
