[package]
authors = ["Ceri Storey <ceri@lshift.net>"]
name = "stomping"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.6"
failure = "0.1.5"
failure_derive = "0.1.5"

[dev-dependencies]
clap = "2.10.2"
env_logger = "0.7.0"
url = "2.0.0"
uuid = { version = "0.8.0", features = ["v4"] }


[features]
# To skip end to end tests on CI
skip-end-to-end = []
